#!/usr/bin/env python3
"""ShoulderAngels — two voices debate your coding path forward.

A "safe" angel and a "bold" angel each propose a development strategy for the
same task. You (or your pipeline) pick one, and the tool predicts concrete
outcomes for the path you chose. Every decision is recorded to a local history
file so you can revisit the forks in the road later.

Originally autogenerated by NICHE (the AutoProjects Organism) under the
Autonomous Tool Creation Protocol; hardened to production quality by hand.

  Novelty: 87/100 (HIGHLY NOVEL) · Closest prior art: PatchNotes (11%)
  Biome: DEV/BUILD · Core mechanism: an embedded LLM call (Completer)

Author: NICHE / Team Brain   For: Logan Smith / Metaphy LLC   License: MIT

Runtime dependencies: the Python standard library only.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shlex
import subprocess
import sys
import time
import urllib.error
import urllib.request
from collections.abc import Callable, Sequence
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

__version__ = "1.1.1"

# The embedded reasoning model. Override per-call with --model or the
# ANTHROPIC_MODEL environment variable.
DEFAULT_MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-haiku-4-5")
DEFAULT_MAX_TOKENS = 1024
API_URL = "https://api.anthropic.com/v1/messages"
ANTHROPIC_VERSION = "2023-06-01"

VALID_CHOICES = ("safe", "bold")
VALID_BACKENDS = ("anthropic", "command")


# --------------------------------------------------------------------------- #
# Embedded LLM core (shared shape across all Organism tools)
# --------------------------------------------------------------------------- #
class LLMError(RuntimeError):
    """Raised when the embedded model cannot be reached or returns garbage."""


@runtime_checkable
class Completer(Protocol):
    """Duck-type contract for anything that can supply a completion.

    Agent hosts (Grok Bot, a subagent, a recorded fixture) implement this
    instead of calling Anthropic. ``ShoulderAngels`` only needs ``complete``.
    """

    def complete(self, prompt: str, system: str = "") -> str: ...


class LLMClient:
    """Minimal, dependency-free client for the Anthropic Messages API.

    Designed to fail loudly and helpfully: a missing key, a network blip, or a
    malformed response each produce a clear ``LLMError`` instead of an opaque
    stack trace. Transient HTTP errors (429/5xx) are retried with backoff.
    """

    def __init__(
        self,
        model: str = DEFAULT_MODEL,
        max_tokens: int = DEFAULT_MAX_TOKENS,
        timeout: float = 60.0,
        max_retries: int = 3,
        api_key: str | None = None,
        api_url: str = API_URL,
    ) -> None:
        self.model = model
        self.max_tokens = max_tokens
        self.timeout = timeout
        self.max_retries = max(1, max_retries)
        self._api_key = api_key
        self.api_url = api_url

    @property
    def api_key(self) -> str:
        key = self._api_key or os.environ.get("ANTHROPIC_API_KEY")
        if not key:
            raise LLMError(
                "ANTHROPIC_API_KEY is not set. Export your key first:\n"
                "    export ANTHROPIC_API_KEY=sk-ant-..."
            )
        return key

    def complete(self, prompt: str, system: str = "") -> str:
        """Send a single-turn prompt and return the model's text response."""
        body: dict[str, Any] = {
            "model": self.model,
            "max_tokens": self.max_tokens,
            "messages": [{"role": "user", "content": prompt}],
        }
        if system:
            body["system"] = system

        data = json.dumps(body).encode("utf-8")
        last_err: Exception | None = None

        for attempt in range(1, self.max_retries + 1):
            req = urllib.request.Request(
                self.api_url,
                data=data,
                headers={
                    "x-api-key": self.api_key,
                    "anthropic-version": ANTHROPIC_VERSION,
                    "content-type": "application/json",
                },
            )
            try:
                with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                    payload = json.loads(resp.read().decode("utf-8"))
                return self._extract_text(payload)
            except urllib.error.HTTPError as exc:
                detail = exc.read().decode("utf-8", "replace")[:500]
                if exc.code in (408, 429, 500, 502, 503, 529) and attempt < self.max_retries:
                    time.sleep(min(2.0 * attempt, 8.0))
                    last_err = exc
                    continue
                raise LLMError(f"API HTTP {exc.code}: {detail}") from exc
            except urllib.error.URLError as exc:
                if attempt < self.max_retries:
                    time.sleep(min(2.0 * attempt, 8.0))
                    last_err = exc
                    continue
                raise LLMError(f"Network error reaching the model: {exc.reason}") from exc
            except (KeyError, IndexError, ValueError) as exc:
                raise LLMError(f"Unexpected API response shape: {exc}") from exc

        raise LLMError(f"Exhausted {self.max_retries} retries: {last_err}")

    @staticmethod
    def _extract_text(payload: dict[str, Any]) -> str:
        content = payload.get("content")
        if not content:
            raise LLMError(f"API returned no content: {payload}")
        parts = [block.get("text", "") for block in content if block.get("type") == "text"]
        text = "".join(parts).strip()
        if not text:
            raise LLMError("API returned an empty text response")
        return text


AnthropicClient = LLMClient


class CallableClient:
    """Wrap any ``(prompt, system) -> text`` callable as a :class:`Completer`."""

    def __init__(self, fn: Callable[[str, str], str]) -> None:
        self._fn = fn

    def complete(self, prompt: str, system: str = "") -> str:
        text = self._fn(prompt, system)
        if not isinstance(text, str) or not text.strip():
            raise LLMError("Callable completer returned empty output")
        return text


class CommandClient:
    """Run an external command as a :class:`Completer`.

    Writes one JSON object ``{"prompt": ..., "system": ...}`` to the child's
    stdin. Reads stdout as JSON ``{"text": ...}`` or as raw text. Raises
    ``LLMError`` on non-zero exit, empty output, or timeout.
    """

    def __init__(
        self,
        command: str | Sequence[str],
        timeout: float = 60.0,
    ) -> None:
        if isinstance(command, str):
            self.command = shlex.split(command)
        else:
            self.command = list(command)
        if not self.command:
            raise LLMError("complete command is empty")
        self.timeout = timeout

    def complete(self, prompt: str, system: str = "") -> str:
        payload = json.dumps({"prompt": prompt, "system": system}).encode("utf-8")
        try:
            proc = subprocess.run(
                self.command,
                input=payload,
                capture_output=True,
                timeout=self.timeout,
            )
        except subprocess.TimeoutExpired as exc:
            raise LLMError(
                f"complete command timed out after {self.timeout}s"
            ) from exc
        except OSError as exc:
            raise LLMError(f"failed to run complete command: {exc}") from exc

        if proc.returncode != 0:
            err = (proc.stderr or b"").decode("utf-8", "replace")[:500]
            raise LLMError(f"complete command exited {proc.returncode}: {err}")

        return self._parse_output((proc.stdout or b"").decode("utf-8", "replace"))

    @staticmethod
    def _parse_output(stdout: str) -> str:
        text = stdout.strip()
        if not text:
            raise LLMError("complete command returned empty output")
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return text
        if isinstance(parsed, dict) and "text" in parsed:
            out = parsed["text"]
            if not isinstance(out, str) or not out.strip():
                raise LLMError("complete command returned empty text")
            return out
        return text


def extract_json(text: str) -> Any:
    """Best-effort parse of a JSON value embedded in arbitrary model output.

    Handles raw JSON, ```json fenced blocks, and JSON preceded by prose.
    Returns the parsed value, or raises ``ValueError`` if nothing parses.
    """
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    fence = re.search(r"```(?:json)?\s*(.*?)```", text, re.DOTALL)
    if fence:
        try:
            return json.loads(fence.group(1).strip())
        except json.JSONDecodeError:
            pass

    # Fall back to the first balanced {...} or [...] span.
    for opener, closer in (("{", "}"), ("[", "]")):
        start = text.find(opener)
        end = text.rfind(closer)
        if 0 <= start < end:
            try:
                return json.loads(text[start : end + 1])
            except json.JSONDecodeError:
                continue
    raise ValueError("No parseable JSON found in model output")


# --------------------------------------------------------------------------- #
# Tool
# --------------------------------------------------------------------------- #
class ShoulderAngels:
    """Generate, choose between, and forecast safe vs. bold dev strategies."""

    STRATEGY_SYSTEM = (
        "You are a development strategist. For the user's task, return ONLY a "
        "JSON object with two keys, 'safe' and 'bold'. 'safe' is the boring, "
        "low-risk, guaranteed approach; 'bold' is the ambitious, experimental, "
        "higher-risk approach. Each value is an object with keys: 'description', "
        "'effort' (low|medium|high), 'risk' (low|medium|high), and 'upside' "
        "(a short phrase). Output JSON only, no prose."
    )

    def __init__(self, store: Path | None = None, client: Completer | None = None) -> None:
        self.store = store or Path.home() / ".shoulderangels" / "history.json"
        self.client = client or LLMClient()

    # -- core mechanism: the embedded LLM ----------------------------------- #
    def _ask(self, prompt: str, system: str = "") -> str:
        """Query the embedded reasoning model (the tool's core mechanism)."""
        return self.client.complete(prompt, system=system)

    # -- strategy generation ------------------------------------------------ #
    def propose(self, target: str) -> dict[str, dict[str, Any]]:
        """Return validated {'safe': {...}, 'bold': {...}} strategies."""
        raw = self._ask(
            f"Task: {target}\n\nProvide two competing development strategies.",
            system=self.STRATEGY_SYSTEM,
        )
        try:
            parsed = extract_json(raw)
        except ValueError:
            parsed = {}
        return self._normalize(parsed, raw)

    @staticmethod
    def _normalize(parsed: Any, raw: str) -> dict[str, dict[str, Any]]:
        if not isinstance(parsed, dict):
            parsed = {}
        out: dict[str, dict[str, Any]] = {}
        for key in VALID_CHOICES:
            val = parsed.get(key)
            if not isinstance(val, dict):
                val = {"description": (raw.strip() or f"No {key} strategy returned")[:280]}
            val.setdefault("description", f"No {key} description")
            val.setdefault("effort", "unknown")
            val.setdefault("risk", "low" if key == "safe" else "high")
            val.setdefault("upside", "n/a")
            out[key] = val
        return out

    def forecast(self, strategy: dict[str, Any]) -> str:
        """Predict three concrete outcomes for the chosen strategy."""
        desc = strategy.get("description", "")
        return self._ask(
            f"Predict realistic outcomes if we pursue this approach:\n{desc}\n\n"
            "List exactly 3 concrete, specific results.",
            system="Be specific and practical. No hedging.",
        )

    # -- orchestration ------------------------------------------------------ #
    def run(
        self,
        target: str,
        choice: str | None = None,
        chooser: Callable[[dict[str, dict[str, Any]]], str] | None = None,
        store: bool = True,
    ) -> dict[str, Any]:
        """Full flow: propose → choose → forecast → record.

        ``choice`` forces a path ('safe'/'bold'/'both'). If omitted and a
        ``chooser`` is supplied, it is asked interactively. With neither, the
        decision defaults to 'safe' (pipeline-friendly, never blocks).
        """
        target, subject = self._bind_subject(target)
        strategies = self.propose(target)

        if choice is None and chooser is not None:
            choice = chooser(strategies)
        if choice is None:
            choice = "safe"
        choice = choice.strip().lower()

        if choice == "both":
            forecasts = {k: self.forecast(strategies[k]) for k in VALID_CHOICES}
            selected: Any = strategies
        else:
            if choice not in VALID_CHOICES:
                choice = "safe"
            selected = strategies[choice]
            forecasts = {choice: self.forecast(selected)}

        result = {
            "target": target,
            "chosen_path": choice,
            "strategy": selected,
            "predicted_outcomes": forecasts,
            "safe_risk": strategies["safe"].get("risk", "low"),
            "bold_upside": strategies["bold"].get("upside", "high"),
            "timestamp": datetime.now(timezone.utc).isoformat(),
            **subject,
        }
        if store:
            self._record(result)
        return result

    @staticmethod
    def _digest(raw: bytes) -> dict[str, Any]:
        h = hashlib.sha256(raw).hexdigest()
        return {
            "subject_size": len(raw),
            "subject_sha256": h,
            "subject_sha16": h[:16],
        }

    @staticmethod
    def _bind_subject(target: Any) -> tuple[str, dict[str, Any]]:
        """Resolve *target* to prompt text AND a digest of the bytes fed.

        File paths: hash the file bytes as they sit on disk (never the
        stripped text the model sees). Plain strings and dicts: hash
        UTF-8 of the text that will be proposed on. Size is always
        bytes, never a character count.
        """
        meta: dict[str, Any] = {"subject_kind": "text"}
        if isinstance(target, dict):
            text = target.get("task") or target.get("target") or json.dumps(target)
            meta.update(ShoulderAngels._digest(text.encode("utf-8")))
            return text, meta
        if isinstance(target, str):
            candidate = Path(target)
            try:
                if candidate.is_file():
                    raw = candidate.read_bytes()
                    meta = {
                        "subject_kind": "file",
                        "subject_path": str(candidate.resolve()),
                        **ShoulderAngels._digest(raw),
                    }
                    return raw.decode("utf-8").strip(), meta
            except OSError:
                pass
            meta.update(ShoulderAngels._digest(target.encode("utf-8")))
            return target, meta
        text = str(target)
        meta.update(ShoulderAngels._digest(text.encode("utf-8")))
        return text, meta

    @staticmethod
    def _coerce_target(target: Any) -> str:
        """Accept a plain string, a JSON object/dict, or a file path."""
        text, _ = ShoulderAngels._bind_subject(target)
        return text

    # -- history persistence ------------------------------------------------ #
    def record(self, result: dict[str, Any]) -> None:
        """Append a finished result dict to history without calling the model.

        Agent hosts that already have a completed decision can persist it here
        instead of re-running ``propose`` / ``run``.
        """
        if not isinstance(result, dict):
            raise TypeError("result must be a dict")
        self._record(result)

    def _record(self, result: dict[str, Any]) -> None:
        history = self.load_history()
        history.append(result)
        self.store.parent.mkdir(parents=True, exist_ok=True)
        self.store.write_text(json.dumps(history, indent=2), encoding="utf-8")

    def load_history(self) -> list[dict[str, Any]]:
        if not self.store.exists():
            return []
        try:
            data = json.loads(self.store.read_text(encoding="utf-8"))
            return data if isinstance(data, list) else []
        except (json.JSONDecodeError, OSError):
            return []


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def _interactive_chooser(strategies: dict[str, dict[str, Any]]) -> str:
    print(f"\n🔰 SAFE PATH: {strategies['safe'].get('description', 'N/A')}")
    print(f"   effort={strategies['safe'].get('effort')} "
          f"risk={strategies['safe'].get('risk')} upside={strategies['safe'].get('upside')}")
    print(f"\n⚡ BOLD PATH: {strategies['bold'].get('description', 'N/A')}")
    print(f"   effort={strategies['bold'].get('effort')} "
          f"risk={strategies['bold'].get('risk')} upside={strategies['bold'].get('upside')}")
    try:
        answer = input("\nChoose [safe/bold/both]: ").strip().lower()
    except EOFError:
        answer = "safe"
    return answer or "safe"


def _env_backend() -> str:
    raw = os.environ.get("SHOULDERANGELS_BACKEND", "anthropic").strip().lower()
    return raw or "anthropic"


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="shoulderangels",
        description="Two voices debate your coding path forward.",
    )
    ap.add_argument("target", nargs="?", help="the task/goal, or a path to a file describing it")
    ap.add_argument("--choose", choices=("safe", "bold", "both"),
                    help="force a path without prompting (pipeline-friendly)")
    ap.add_argument("--json", action="store_true", help="emit JSON")
    ap.add_argument("--model", default=DEFAULT_MODEL, help=f"model id (default: {DEFAULT_MODEL})")
    ap.add_argument("--max-tokens", type=int, default=DEFAULT_MAX_TOKENS, help="max tokens per call")
    ap.add_argument(
        "--backend",
        choices=VALID_BACKENDS,
        default=_env_backend(),
        help="completion backend (default: anthropic; also $SHOULDERANGELS_BACKEND)",
    )
    ap.add_argument(
        "--complete-cmd",
        default=os.environ.get("SHOULDERANGELS_COMPLETE_CMD"),
        metavar="CMD",
        help="external completer command; required for --backend command "
             "(also $SHOULDERANGELS_COMPLETE_CMD)",
    )
    ap.add_argument("--no-store", action="store_true", help="do not record this decision to history")
    ap.add_argument("--history", action="store_true", help="print decision history and exit")
    ap.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    return ap


def client_from_args(args: argparse.Namespace) -> Completer:
    """Build a Completer from parsed CLI flags. Anthropic stays the default."""
    backend = (args.backend or "anthropic").strip().lower()
    if backend == "command":
        cmd = (args.complete_cmd or "").strip()
        if not cmd:
            build_parser().error(
                "--complete-cmd is required when --backend is command "
                "(or set SHOULDERANGELS_COMPLETE_CMD)"
            )
        return CommandClient(cmd)
    if backend != "anthropic":
        build_parser().error(
            f"invalid --backend {args.backend!r} (choose from {', '.join(VALID_BACKENDS)})"
        )
    return LLMClient(model=args.model, max_tokens=args.max_tokens)


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    if args.history:
        # History does not call the model; skip backend / API-key requirements.
        tool = ShoulderAngels()
        history = tool.load_history()
        print(json.dumps(history, indent=2) if args.json else f"{len(history)} decision(s) recorded")
        if not args.json:
            for item in history:
                print(f"  • [{item.get('chosen_path')}] {item.get('target')}")
        return 0

    if not args.target:
        build_parser().error("a target task is required (or use --history)")

    # Interactive only when attached to a TTY and no choice was forced.
    chooser = _interactive_chooser if (args.choose is None and sys.stdin.isatty()) else None

    try:
        tool = ShoulderAngels(client=client_from_args(args))
        result = tool.run(
            args.target,
            choice=args.choose,
            chooser=chooser,
            store=not args.no_store,
        )
    except LLMError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(f"\n✅ Chosen path: {result['chosen_path']}")
        for path, outcome in result["predicted_outcomes"].items():
            print(f"\n— Predicted outcomes ({path}) —\n{outcome}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
